require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewlettersController do

  # This should return the minimal set of attributes required to create a valid
  # Newletter. As you add validations to Newletter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all newletters as @newletters" do
      newletter = Newletter.create! valid_attributes
      get :index
      assigns(:newletters).should eq([newletter])
    end
  end

  describe "GET show" do
    it "assigns the requested newletter as @newletter" do
      newletter = Newletter.create! valid_attributes
      get :show, :id => newletter.id
      assigns(:newletter).should eq(newletter)
    end
  end

  describe "GET new" do
    it "assigns a new newletter as @newletter" do
      get :new
      assigns(:newletter).should be_a_new(Newletter)
    end
  end

  describe "GET edit" do
    it "assigns the requested newletter as @newletter" do
      newletter = Newletter.create! valid_attributes
      get :edit, :id => newletter.id
      assigns(:newletter).should eq(newletter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newletter" do
        expect {
          post :create, :newletter => valid_attributes
        }.to change(Newletter, :count).by(1)
      end

      it "assigns a newly created newletter as @newletter" do
        post :create, :newletter => valid_attributes
        assigns(:newletter).should be_a(Newletter)
        assigns(:newletter).should be_persisted
      end

      it "redirects to the created newletter" do
        post :create, :newletter => valid_attributes
        response.should redirect_to(Newletter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newletter as @newletter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newletter.any_instance.stub(:save).and_return(false)
        post :create, :newletter => {}
        assigns(:newletter).should be_a_new(Newletter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newletter.any_instance.stub(:save).and_return(false)
        post :create, :newletter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newletter" do
        newletter = Newletter.create! valid_attributes
        # Assuming there are no other newletters in the database, this
        # specifies that the Newletter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newletter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => newletter.id, :newletter => {'these' => 'params'}
      end

      it "assigns the requested newletter as @newletter" do
        newletter = Newletter.create! valid_attributes
        put :update, :id => newletter.id, :newletter => valid_attributes
        assigns(:newletter).should eq(newletter)
      end

      it "redirects to the newletter" do
        newletter = Newletter.create! valid_attributes
        put :update, :id => newletter.id, :newletter => valid_attributes
        response.should redirect_to(newletter)
      end
    end

    describe "with invalid params" do
      it "assigns the newletter as @newletter" do
        newletter = Newletter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newletter.any_instance.stub(:save).and_return(false)
        put :update, :id => newletter.id, :newletter => {}
        assigns(:newletter).should eq(newletter)
      end

      it "re-renders the 'edit' template" do
        newletter = Newletter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newletter.any_instance.stub(:save).and_return(false)
        put :update, :id => newletter.id, :newletter => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newletter" do
      newletter = Newletter.create! valid_attributes
      expect {
        delete :destroy, :id => newletter.id
      }.to change(Newletter, :count).by(-1)
    end

    it "redirects to the newletters list" do
      newletter = Newletter.create! valid_attributes
      delete :destroy, :id => newletter.id
      response.should redirect_to(newletters_url)
    end
  end

end
